name: Yarn
on: [pull_request]
jobs:
  yarn_lock_changes:
    name: Lock File Changes
    runs-on: ubuntu-latest
    # Permission overwrite is required for Dependabot PRs
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Digest Lock File
        uses: Simek/yarn-lock-changes@a14bb956a5880a7031bedd6f3017fa6853793ea2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          collapsibleThreshold: 25
          failOnDowngrade: false
          path: yarn.lock
          updateComment: true
